### ISSUE TITLE
Is this ready for a 1.x-2.0.0 release?

### ISSUE THREAD

**Issue by kreynen** [backdrop-contrib/simplesamlphp_auth#1]
I mentioned https://github.com/simplesamlphp/simplesamlphp/issues/1689 and this module as a potential solution for the Symfony 6 compatibility issues. We're working on the scope of work to migrate a few CU sites to Backdrop.

**Comment by kreynen** [comment]
I talked to @joelsteidl about this yesterday. While I'd like to see https://github.com/backdrop-contrib/simplesamlphp_auth/issues/4 and https://github.com/backdrop-contrib/simplesamlphp_auth/issues/5, resolving https://github.com/backdrop-contrib/simplesamlphp_auth/issues/2 was really the only blocker.

If this is running at multiple organizations with different SAML configurations ([Stanford](https://opensource.stanford.edu/sunet-authentication-drupal-using-simplesamlphp) and the [University of Colorado](https://github.com/cu-uis/cu-starterkit-project/wiki/Building:SAML-Configuration)), is there any reason not to [push a 1.0.0 release](https://github.com/backdrop-ops/contrib#releases)?

**Comment by irinaz** [comment]
I think that we can move forward with release asap. If we find any bugs, we will fix them.

**Comment by joelsteidl** [comment]
I have no issue with a release @kreynen .

**Comment by argiepiano** [comment]
One thing to fix before releasing simplesamlphp_auth: it seems like the current Backdrop version is based on `7-x.2.0-alhpa2` (please confirm). We usually want to keep a matching major version number when we port to Backdrop, so the correct version would be `1.x-2.0.0-alpha1`

And the correct dev version should be `1.x-2.x` rather than 1.x-1.x

**Comment by joelsteidl** [comment]
@argiepiano correct, started from [7.x-2.0-alpha2](https://www.drupal.org/project/simplesamlphp_auth/releases/7.x-2.0-alpha2)

**Comment by argiepiano** [comment]
Thanks. Then it'd be a good idea to rename the dev branch before releasing

**Comment by joelsteidl** [comment]
i see.  @kreynen any issue with me doing that now? I don't think there are outstanding PRs

**Comment by kreynen** [comment]
This all makes sense to me. It lets @irinaz move forward, doesn't block/disrupt any other work and gives any future users a better sense of where the code came from and the current state.

@joelsteidl feel free to create the 1.x-2.0 branch, `git tag 1.x-2.0.0-alpha2` and push that. 

Well continue working on cleaning this up and moving towards a 2.0.0 release after that

**Comment by irinaz** [comment]
Perfect - thank you so much!  I will uninstall current version and install released version when it is ready.  @joelsteidl , @kreynen @argiepiano - thanks a lot!

**Comment by joelsteidl** [comment]
@kreynen I renamed the `1.x-1.x` branch as `1.x.2.x` and tagged a release https://github.com/backdrop-contrib/simplesamlphp_auth/tags

**Comment by argiepiano** [comment]
I see a tag but not a release. You may want to go through with a release. Doing a release has the benefit that Backdrop's Installer will be able to find the module through the Backdrop module portal. Backdrop will package the module with the version, which makes it very convenient when there is a new release - your site will indicate that a new release is ready. 

As it is right now, the module has not been packaged, and it's not appearing in the Backdrop list of modules.

**Comment by kreynen** [comment]
https://github.com/backdrop-ops/contrib#releases makes is sound like you only need to push a tag.

```
2. Push the tag up to the contrib repository.
3. Visit the page for the tag in GitHub, and create a release from that page.
4. Wait about 5 seconds, then refresh the GitHub release page.

```

Is that not accurate? Does someone need to follow the steps in the normal [GitHub release process](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository)?

**Comment by argiepiano** [comment]
All is good now. I didn't see the release when I first checked. Now it's there, and has been picked up by backdropcms.org

**Comment by kreynen** [comment]
Great. Showing up on https://backdropcms.org/modules now too. @joelsteidl did you have to do anything else?

Is the issue that it works, but takes longer than 5 seconds now?

<img width="929" alt="Screen Shot 2022-11-17 at 12 04 06 PM" src="https://user-images.githubusercontent.com/385234/202535681-fe00e666-7471-4ea0-8cbf-ad0d76a2a553.png">

**Comment by joelsteidl** [comment]
@argiepiano @kreynen I created a release.

**Comment by irinaz** [comment]
@kreynen , should we mark this issue closed?  thanks you, @kreynen @joelsteidl @argiepiano !!!

**Comment by laryn** [comment]
I merged a bunch of bug fixes today. @kreynen @argiepiano @irinaz, do you care to test before I make a next release? (I think I already have most of these patches running on the sites in question but I'm also going to test the latest on a few dev sites of my own.)
