### ISSUE TITLE
Undefined constant "BACKDROP_AUTHENTICATED_RID"

### ISSUE THREAD

**Issue by kreynen** [backdrop-contrib/simplesamlphp_auth#2]
https://github.com/backdrop-contrib/simplesamlphp_auth/blob/1.x-1.x/simplesamlphp_auth.install#L13

We used https://www.drupal.org/project/noreqnewpass in D7 sites using SSO, so I understand why you'd want to remove a `change own password`. I just don't see how this line would actually accomplish this. I commented this line out and I'm seeing the configuration options I expect when using simplesamlphp_auth in D7 or D9.

**Comment by argiepiano** [comment]
Also, a side comment. As noted in the issue title, `BACKDROP_AUTHENTICATED_RID` doesn't exist in Backdrop. We don't use role ids, but rather machine names. Thus, the correct constant is `BACKDROP_AUTHENTICATED_ROLE` (function `user_role_revoke_permissions()` expects a role machine name).

**Comment by argiepiano** [comment]
Also `change own password` is not a permission that exists in Backdrop currently, so this line 13 doesn't really do anything.

The only instance I can find of that permission is the one created by the [userprotect module](https://github.com/backdrop-contrib/userprotect)

**Comment by kreynen** [comment]
Talked to @joelsteidl about this yesterday. Because this module is being used on sites with existing D7 databases and the Backdrop module uses the same namespace as the D7 module, the install isn't run on those projects. 

This line is a direct port of https://git.drupalcode.org/project/simplesamlphp_auth/-/blob/7.x-3.x/simplesamlphp_auth.install#L13

I created [a PR](https://github.com/backdrop-contrib/simplesamlphp_auth/pull/3) to remove that line.
