### ISSUE TITLE
simplesamlphp_auth module fails because no authmap module, but authmap not available to install.

### ISSUE THREAD

**Issue by marcus-leonard** [backdrop-contrib/simplesamlphp_auth#27]
Not sure if I should be posting this to the simplesamlphp_auth queue or the authmap queue, but posting here because it happens when trying to install simplesamlphp_auth.

Install message:
simpleSAMLphp authentication | 1.x-2.0.0-alpha2 | authmap (missing)

I can get authmap from github, but I note that it currently has no releases. (It also has no issues. :smile: )

Can I just install authmap from github and will that allow simplesamlphp_auth to work?

**Comment by marcus-leonard** [comment]
The workaround is to manually install authmap module to bd modules directory and enable.
simplesamlphp_auth module will then cheerfully install.

I could close this since my problem is solved, but I'm wondering if this should be left open since it is technically an issue if someone tries to install this module through the UI?
I'm happy if someone decides it should be closed.

**Comment by laryn** [comment]
@marcus-leonard 
Let's leave it open for now. I've also cross-posted in the Authmap queue about making a release.

**Comment by laryn** [comment]
We have a 1.x-1.0.0 release for Authmap now, so I'll close this.
