### ISSUE TITLE
Call to undefined function `user_external_login_register()`

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/simplesamlphp_auth#34]
While porting and testing the module `backdropauth4ssp` (in D7 it's called `drupalauth4ssp`) I ran into this error. 

The problem is that `simplesamlphp_auth_init()` is still calling  `user_external_login_register()`, which doesn't exist anymore. Currently, this function exists in the submodule `authmap` and is called `authmap_external_login_register()`.

**Comment by laryn** [comment]
Thank you @argiepiano!
