### ISSUE TITLE
Remove the correct variables in `simplesamlphp_auth_update_1000()` 

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/simplesamlphp_auth#8]
All the `update_variable_del()` calls in `simplesamlphp_auth_update_1000()` pass the wrong variable names to the delete function. For example, you want to delete `simplesamlphp_auth_activate`, not `activate` (which doesn't exist). 

This means that all those D7 variables are kept in the database even after the upgrade.

**Comment by laryn** [comment]
👍  I noticed this, too, when looking at another issue.
